// One-time import: parse the SHEETS array out of the firm's checklist HTML and
// emit versioned template records.
//
//   npm run templates:import [-- path/to/checklists.html]
//
// Writes:
//   templates/GL-A1.v1.json ... GL-A6.v1.json   (reviewable JSON)
//   supabase/migrations/20260923000500_seed_templates_v1.sql
//
// The HTML's inline script is evaluated in an isolated vm context up to the
// render code, so controlSec()/recordsSec() expand exactly as they do in the
// browser. Nothing is hand-transcribed.

import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import vm from 'node:vm'
import { RENDER_MARKER, convertSheets, type SheetSource } from '../lib/templates/convert'

const ROOT = join(__dirname, '..')
const SRC = process.argv[2] ?? join(ROOT, 'reference', 'Gasper_Legal_Asset_Intake_Checklists.html')
const VERSION = 1
const SEED_FILE = join(ROOT, 'supabase', 'migrations', '20260923000500_seed_templates_v1.sql')

// ---------- load SHEETS from the HTML ----------
function loadSource(path: string): SheetSource {
  const html = readFileSync(path, 'utf8')
  const m = html.match(/<script>([\s\S]*?)<\/script>/)
  if (!m) throw new Error('No inline <script> found')
  const cut = m[1].indexOf(RENDER_MARKER)
  if (cut < 0) throw new Error('Render marker not found; the HTML layout changed')
  const code = m[1].slice(0, cut) + '\n;({SHEETS, MATTER, SIGNOFF})'
  return vm.runInNewContext(code, Object.create(null), { timeout: 1000 })
}

// ---------- emit ----------
function sqlLiteral(s: string): string {
  return `'${s.replace(/'/g, "''")}'`
}

function main() {
  const { SHEETS, MATTER, SIGNOFF } = loadSource(SRC)
  const templates = convertSheets({ SHEETS, MATTER, SIGNOFF })

  const codes = templates.map((t) => t.code).join(',')
  if (codes !== 'GL-A1,GL-A2,GL-A3,GL-A4,GL-A5,GL-A6') throw new Error(`Unexpected sheet codes: ${codes}`)

  for (const t of templates) {
    const json = JSON.stringify(t, null, 2) + '\n'
    if (/[^\x00-\x7F]/.test(json)) throw new Error(`${t.code} still has non-ASCII text`)
    writeFileSync(join(ROOT, 'templates', `${t.code}.v${VERSION}.json`), json)
    const n = Object.keys(t.keys).length
    console.log(`${t.code} ${t.title}: ${t.sections.length} sections, ${n} storable keys`)
  }

  const lines = [
    '-- GENERATED by scripts/import-templates.ts from reference/Gasper_Legal_Asset_Intake_Checklists.html.',
    '-- Do not edit by hand. Templates are immutable once inserted; revisions are new versions.',
    '',
    'insert into public.templates (code, name, version, schema, accent) values',
    templates
      .map(
        (t) =>
          `  (${sqlLiteral(t.code)}, ${sqlLiteral(t.title)}, ${VERSION}, ${sqlLiteral(JSON.stringify(t))}::jsonb, ${sqlLiteral(t.accent)})`,
      )
      .join(',\n') + ';',
    '',
  ]
  writeFileSync(SEED_FILE, lines.join('\n'))
  console.log(`Wrote ${SEED_FILE}`)
}

main()
